os: linux
language: c

jobs:
  include:
    - env: CABALVER=3.2 GHCVER=head
      addons:
        apt:
          packages: [cabal-install-3.2, ghc-head]
          sources: [hvr-ghc]
    - env: CABALVER=3.2 GHCVER=8.10.2
      addons:
        apt:
          packages: [cabal-install-3.2, ghc-8.10.2]
          sources: [hvr-ghc]
    - env: CABALVER=3.2 GHCVER=8.8.4
      addons:
        apt:
          packages: [cabal-install-3.2, ghc-8.8.4]
          sources: [hvr-ghc]
    - env: CABALVER=3.2 GHCVER=8.6.5
      addons:
        apt:
          packages: [cabal-install-3.2, ghc-8.6.5]
          sources: [hvr-ghc]
    - env: CABALVER=3.2 GHCVER=8.4.4
      addons:
        apt:
          packages: [cabal-install-3.2, ghc-8.4.4]
          sources: [hvr-ghc]
    - env: CABALVER=3.2 GHCVER=8.2.2
      addons:
        apt:
          packages: [cabal-install-3.2, ghc-8.2.2]
          sources: [hvr-ghc]
  allow_failures:
    - env: CABALVER=3.2 GHCVER=head

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
  - |
    set -e
    cabal --version
    echo "$(ghc --version) "`
        `"[$(ghc --print-project-git-commit-id 2>/dev/null || echo '?')]"
    travis_retry cabal v1-update
    cabal v1-install --only-dependencies
    set +e

script:
  - |
    set -e
    cabal v1-configure
    cabal v1-build
    cabal v2-sdist --builddir=dist
    SRC_TGZ=$(cabal info . | awk '{print $2; exit}').tar.gz &&
        (cd dist/sdist && cabal v1-install --force-reinstalls "$SRC_TGZ")
    set +e

